name: ci-build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  ci-lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with: { go-version: 1.19 }
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  ci-test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with: { go-version: 1.19 }
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - uses: actions/checkout@v3
      - name: Install Taskfile
        run: curl -sL https://taskfile.dev/install.sh | sh
      - name: Run tests
        run: ./bin/task -v test
      - name: Upload log files
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: go-jira-tools.log
          path: |
            /tmp/go-jira-tools.log
          if-no-files-found: error
