name: ci-build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  ci-lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20.3
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
  ci-test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: 1.20.3 }
      - name: Install Taskfile
        run: curl -sL https://taskfile.dev/install.sh | sh
      - name: Run tests
        run: ./bin/task -v ci-test
      - name: Upload log files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: go-jira-tools.log
          path: |
            /tmp/go-jira-tools.log
          if-no-files-found: error
